name: Build and publish docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mike
      - run: pip install mkdocs-material
      - run: pip install mkdocs-render-swagger-plugin
      - run: mike deploy --push --rebase --update-aliases dev
