name: CI

on:
  pull_request:
    branches:
      - main
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mike
      - run: pip install mkdocs-material
      - run: pip install mkdocs-render-swagger-plugin
      - run: pip install git+https://github.com/it-novum/mkdocs-featherlight.git
      - run: mkdocs build --strict
